services:
  database:
    image: "postgres:17.1-alpine"
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - ./back/.env
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - database-network

  back:
    build:
      context: back/
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./back/src
          target: /app/src
          ignore:
            - node_modules/
    depends_on:
      - database
    networks:
      - database-network

  front:
    build:
      context: front/
      dockerfile: Dockerfile.dev
    ports:
        - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front/src
          target: /app/src
          ignore:
            - node_modules/
    depends_on:
      - database
    networks:
      - back

  grafana:
    image: grafana/grafana:11.5.1

    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - database
    networks:
      - database-network
      - prometheus-network

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:master
    container_name: postgres_exporter
    env_file:
      - ./back/.env
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}?sslmode=disable
    networks:
      - database-network
      - postgres-exporter-network

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - database-network
      - prometheus-network
      - postgres-exporter-network



volumes:
  database-data:
  grafana-data:

networks:
  back:
    driver: bridge
  database-network:
    driver: bridge
  prometheus-network:
    driver: bridge
  postgres-exporter-network:
    driver: bridge
