FROM node:23-alpine3.20 AS builder

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile && \
    yarn build && \
    rm -rf node_modules

FROM node:23-alpine3.20

WORKDIR /app

COPY --from=builder /app/build ./build
RUN yarn global add serve

EXPOSE 3000

CMD ["sh", "-c", "serve -s build -l 3000 --no-clipboard > /dev/null"]
